### ISSUE TITLE
the editor won't start

### ISSUE THREAD

**Issue by ghoshbinayak** [processing/p5.js-editor#212]
trying to run p5.js-editor on linux (`npm run app`)  I get the following error:

**Using: npm@3.5.3, node@v5.5.0**

```
[6549:0225/030257:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[6590:0225/030300:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[6549:0225/030301:ERROR:nw_shell.cc(336)] TypeError: undefined is not a function
    at Object.8../files (file:///home/binayak/projects/p5.js-editor/public/js/main.js:1039:11)
    at s (file:///home/binayak/projects/p5.js-editor/public/js/main.js:1:220)
    at file:///home/binayak/projects/p5.js-editor/public/js/main.js:1:271
    at Object.7../debug/index (file:///home/binayak/projects/p5.js-editor/public/js/main.js:485:12)
    at s (file:///home/binayak/projects/p5.js-editor/public/js/main.js:1:220)
    at e (file:///home/binayak/projects/p5.js-editor/public/js/main.js:1:391)
    at file:///home/binayak/projects/p5.js-editor/public/js/main.js:1:409
[6549:0225/030301:INFO:CONSOLE(1039)] "Uncaught TypeError: undefined is not a function", source: file:///home/binayak/projects/p5.js-editor/public/js/main.js (1039)
```

**Comment by b2renger** [comment]
Same here using npm 3.3.12 and nvm 5.2.0

However running 'gulp' task didn't complete, it just hung without any error messages.

@ghoshbinayak did gulp complete ?

**Comment by ghoshbinayak** [comment]
@b2renger there is a `watch` task which keeps on running. The rest completes successfully.
