### ISSUE TITLE
Unhandled exception on Cancel when creating New File

### ISSUE THREAD

**Issue by Akarshit** [processing/p5.js-editor#289]
This exception is thrown when `Cancel` is clicked after selecting `New File` from the menu.
```
TypeError: Cannot read property 'replace' of null
    at ViewModel.appConfig.methods.newFile (file:///Users/akarshitwal/Documents/p5.js-editor/public/js/main.js:952:105)
    at MenuItem.fileMenu.append.gui.MenuItem.click (file:///Users/akarshitwal/Documents/p5.js-editor/public/js/main.js:1206:13)
    at MenuItem.handleEvent (menuitem.js:200:12)
    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)
[69111:1211/181643:INFO:CONSOLE(952)] "Uncaught TypeError: Cannot read property 'replace' of null", source: file:///Users/akarshitwal/Documents/p5.js-editor/public/js/main.js (952)
```

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-editor/pull/290
